### DISCUSSION TITLE
Thoughts on combining arbitrary schemas

### DISCUSSION THREAD

**Discussion by dventimihasura** [graphql/composite-schemas-wg#277] [General]
Hello!

I wanted to introduce a topic for discussion here and offer it as a possible topic for discussion in a Composite WG meeting, on the subject of "combining arbitrary schemas" by which I mean schemas without [Composite Schema directives](https://github.com/graphql/composite-schemas-spec/blob/main/spec/Section%202%20--%20Source%20Schema.md#directives).

I understand that _"the GraphQL Composite Schemas spec does not describe how to combine arbitrary schemas,"_ but does encourage developers _"to design the source schemas...from the start."_  and that totally makes sense.  Still, our experience at [Hasura](https://hasura.io/) with enterprise organizations is that they sometimes have existing GraphQL schemas that they would like to compose, but don't have enough flexibility or collaboration to adapt their schemas to make them compatible with the spec.  Aspects of [data stewardship](https://en.wikipedia.org/wiki/Data_steward) and  [data governance](https://en.wikipedia.org/wiki/Data_governance#Micro_level) sometimes also involve managing cross-domain relationships, outside of those domains.  This also seems to contribute to some of the [Data Mesh principles](https://martinfowler.com/articles/data-mesh-principles.html#FederatedComputationalGovernance) as well.  Does the Composite WG have any thoughts on how to make sub-graphs compatible with the Composite spec in these cases?  Possibly as a source of inspiration, [GraphQL Mesh](https://the-guild.dev/graphql/mesh) from [The Guild](https://the-guild.dev/) can dynamically transform a sub-graph into a Federation-compatible sub-graph.  Examples from [GraphQL Mesh docs](https://the-guild.dev/graphql/mesh/docs/transforms/federation#how-to-use) below.  

What does the WG think of this?  Are there other approaches that have been considered?  Or, is this a runtime concern that's outside the scope of what the WG is trying to achieve?  There are certainly no wrong answers!!  Just trying to learn what the state-of-the-art and prior art are on this topic, if any.  Thanks!

```yaml
transforms:
  - federation:
      types:
        # Ensure the root queries of this schema show up the combined schema
        - name: Query
          config:
            extends: true
        - name: Product
          config:
            # extend Product {
            extend: true
            # Product @key(fields: "id") {
            key:
              fields:
                - id
            fields:
              # id: Int! @external
              - name: id
                config:
                  external: true
            resolveReference:
              queryFieldName: user
```
